import { useCallback, useEffect, useMemo, useState } from 'react'
import { Toaster, toast } from 'react-hot-toast'
import './App.css'

const preferredCodes = ['USD', 'EUR', 'GBP', 'PHP', 'JPY', 'AUD']

function App() {
  const [currencies, setCurrencies] = useState([]), [amount, setAmount] = useState('100'), [from, setFrom] = useState('USD'), [to, setTo] = useState('PHP'), [result, setResult] = useState(null)
  const [token, setToken] = useState(localStorage.getItem('currency_token') || ''), [user, setUser] = useState(null), [panel, setPanel] = useState('convert')
  const [authMode, setAuthMode] = useState('login'), [auth, setAuth] = useState({ name: '', email: '', password: '', password_confirmation: '' }), [showPassword, setShowPassword] = useState(false), [showConfirmation, setShowConfirmation] = useState(false)
  const [dashboard, setDashboard] = useState({ conversions: [], favorites: [], alerts: [] }), [alert, setAlert] = useState({ target_rate: '', condition: 'above' }), [message, setMessage] = useState(''), [error, setError] = useState(''), [fieldErrors, setFieldErrors] = useState({}), [loading, setLoading] = useState(false)
  const request = useCallback(async (path, { authenticated = true, ...options } = {}) => { const response = await fetch(`/api${path}`, { ...options, headers: { Accept: 'application/json', ...(options.body ? { 'Content-Type': 'application/json' } : {}), ...(authenticated && token ? { Authorization: `Bearer ${token}` } : {}) } }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) { const e = new Error(data?.message || Object.values(data?.errors || {})[0]?.[0] || 'Something went wrong.'); e.validation = data?.errors || {}; throw e } return data }, [token])
  const notify = (text) => toast.success(text)
  useEffect(() => { request('/currencies').then((data) => { const list = data.currencies || []; setCurrencies([...list.filter((c) => preferredCodes.includes(c.code)), ...list.filter((c) => !preferredCodes.includes(c.code))]) }).catch((e) => setError(e.message)) }, [request])
  const loadDashboard = useCallback(async () => { if (!token) return; try { const [conversions, favorites, alerts] = await Promise.all([request('/conversions'), request('/favorites'), request('/alerts')]); setDashboard({ conversions: conversions.data || [], favorites: favorites.favorites || [], alerts: alerts.alerts || [] }) } catch (e) { setError(e.message) } }, [request, token])
  useEffect(() => { if (token) request('/user').then((data) => { setUser(data.user); setPanel('dashboard') }).catch(() => { localStorage.removeItem('currency_token'); setToken(''); setUser(null) }) }, [request, token]); useEffect(() => { loadDashboard() }, [loadDashboard])
  useEffect(() => { if (error) { toast.error(error); setError('') } }, [error])
  const options = useMemo(() => currencies, [currencies])
  const convert = async (event, variant = 'demo') => { event.preventDefault(); setLoading(true); setError(''); try { const data = await request('/convert', { authenticated: variant === 'full', method: 'POST', body: JSON.stringify({ amount, from, to }) }); setResult(data); if (variant === 'full') { notify('Conversion saved to your history.'); loadDashboard() } } catch (e) { setError(e.message) } finally { setLoading(false) } }
  const submitAuth = async (event) => { event.preventDefault(); setLoading(true); setError(''); setFieldErrors({}); if (authMode === 'register' && auth.password !== auth.password_confirmation) { setFieldErrors({ password_confirmation: ['Passwords do not match.'] }); setLoading(false); return } try { const data = await request(authMode === 'login' ? '/login' : '/register', { method: 'POST', body: JSON.stringify(auth) }); localStorage.setItem('currency_token', data.token); setToken(data.token); setUser(data.user); setPanel('dashboard'); notify(`Welcome${data.user.name ? `, ${data.user.name}` : ''}!`) } catch (e) { setFieldErrors(e.validation || {}); if (!Object.keys(e.validation || {}).length) setError(e.message) } finally { setLoading(false) } }
  const logout = async () => { try { await request('/logout', { method: 'POST' }) } catch {} localStorage.removeItem('currency_token'); setToken(''); setUser(null); setPanel('convert'); notify('You have been logged out.') }
  const saveFavorite = async () => { try { await request('/favorites', { method: 'POST', body: JSON.stringify({ from, to }) }); notify(`${from}/${to} saved to favorites.`); loadDashboard() } catch (e) { setError(e.message) } }
  const createAlert = async (event) => { event.preventDefault(); try { await request('/alerts', { method: 'POST', body: JSON.stringify({ from, to, ...alert }) }); setAlert({ target_rate: '', condition: 'above' }); notify('Rate alert created.'); loadDashboard() } catch (e) { setError(e.message) } }
  const remove = async (path) => { try { await request(path, { method: 'DELETE' }); notify('Item removed.'); loadDashboard() } catch (e) { setError(e.message) } }
  return <main className={panel === 'dashboard' && user ? 'app-shell dashboard-shell' : 'app-shell'}><Toaster position="top-center" toastOptions={{ duration: 3800, style: { background: '#151c31', color: '#f6f8ff', border: '1px solid rgba(255,255,255,.16)', borderRadius: '12px', boxShadow: '0 18px 44px rgba(0,0,0,.36)' }, success: { iconTheme: { primary: '#5ddb9d', secondary: '#151c31' } }, error: { iconTheme: { primary: '#ff6b8b', secondary: '#151c31' } } }} /><nav className="navbar"><strong>FX<span>Flow</span></strong>{user && <div><button className="text-button" onClick={() => setPanel('dashboard')}>Dashboard</button><button className="text-button" onClick={logout}>Log out</button></div>}</nav>
    {panel === 'auth' ? <AuthPanel mode={authMode} setMode={setAuthMode} auth={auth} setAuth={setAuth} submit={submitAuth} loading={loading} errors={fieldErrors} showPassword={showPassword} setShowPassword={setShowPassword} showConfirmation={showConfirmation} setShowConfirmation={setShowConfirmation} /> : panel === 'dashboard' && user ? <Dashboard dashboard={dashboard} from={from} to={to} setFrom={setFrom} setTo={setFrom === undefined ? setTo : setTo} currencies={options} alert={alert} setAlert={setAlert} createAlert={createAlert} remove={remove} setPanel={setPanel} /> : <section className="hero-panel"><div className="hero-copy"><p className="eyebrow">Currency conversion platform</p><h1>Convert with confidence.</h1><p className="hero-text">Live exchange rates, clear results, saved currency pairs, personal conversion history, and target-rate alerts.</p>{user ? <button className="text-button" onClick={() => setPanel('dashboard')}>Open your dashboard →</button> : <button className="account-cta" onClick={() => setPanel('auth')}>Sign in to save pairs and alerts <span>→</span></button>}</div><div className="converter-card"><form className="converter-form" onSubmit={convert}><label>Amount<input inputMode="decimal" type="number" min="0.01" step="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} /></label><div className="pair-grid"><label>From<Currency value={from} setValue={setFrom} currencies={options} /></label><button type="button" className="swap-button" onClick={() => { setFrom(to); setTo(from); setResult(null) }}>Swap</button><label>To<Currency value={to} setValue={setTo} currencies={options} /></label></div><button className="convert-button" disabled={loading}>{loading ? 'Converting…' : 'Convert now'}</button></form>{user && <button className="text-button save-button" onClick={saveFavorite}>Save this pair</button>}{result ? <div className="result-card result-enter"><p><strong>{Number(result.amount).toLocaleString()}</strong> {result.from}</p><p className="rate-line">1 {result.from} = {Number(result.rate).toFixed(4)} {result.to}</p><h2>{Number(result.converted_amount).toLocaleString()} {result.to}</h2><span className="source-chip">Rate date: {result.fetched_at}</span></div> : <div className="result-card muted">Your converted amount will appear here.</div>}</div></section>}
  </main>
}

function Notice({ type, text, close }) { return <div className={`toast ${type === 'error' ? 'error-toast' : 'success-toast'}`} role={type === 'error' ? 'alert' : 'status'}><span>{type === 'error' ? '!' : '✓'}</span>{text}<button onClick={close} aria-label="Dismiss notification">×</button></div> }
function Field({ label, error, children }) { return <label className={error ? 'field invalid' : 'field'}>{label}{children}{error && <span className="field-error">{error[0]}</span>}</label> }
function PasswordInput({ visible, onToggle, ...props }) { return <span className="password-control"><input {...props} type={visible ? 'text' : 'password'} /><button type="button" onClick={onToggle} aria-label={visible ? 'Hide password' : 'Show password'}>{visible ? 'Hide' : 'Show'}</button></span> }
function AuthPanel({ mode, setMode, auth, setAuth, submit, loading, errors, showPassword, setShowPassword, showConfirmation, setShowConfirmation }) { return <section className="auth-card"><p className="eyebrow">Your account</p><h1>{mode === 'login' ? 'Welcome back' : 'Create an account'}</h1><p className="form-hint">{mode === 'login' ? 'Sign in to sync your history and alerts.' : 'Use 8+ characters with uppercase, lowercase, and a number.'}</p><form className="converter-form" onSubmit={submit} noValidate>{mode === 'register' && <Field label="Name" error={errors.name}><input required autoComplete="name" value={auth.name} onChange={(e) => setAuth({ ...auth, name: e.target.value })} /></Field>}<Field label="Email" error={errors.email}><input required autoComplete="email" type="email" value={auth.email} onChange={(e) => setAuth({ ...auth, email: e.target.value })} /></Field><Field label="Password" error={errors.password}><PasswordInput visible={showPassword} onToggle={() => setShowPassword(!showPassword)} required autoComplete={mode === 'login' ? 'current-password' : 'new-password'} minLength="8" value={auth.password} onChange={(e) => setAuth({ ...auth, password: e.target.value })} /></Field>{mode === 'register' && <Field label="Confirm password" error={errors.password_confirmation}><PasswordInput visible={showConfirmation} onToggle={() => setShowConfirmation(!showConfirmation)} required autoComplete="new-password" value={auth.password_confirmation} onChange={(e) => setAuth({ ...auth, password_confirmation: e.target.value })} /></Field>}<button className="convert-button" disabled={loading}>{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button className="text-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Register' : 'Already registered? Sign in'}</button></section> }
function Currency({ value, setValue, currencies }) { return <select value={value} onChange={(e) => setValue(e.target.value)}>{currencies.map((currency) => <option key={currency.code} value={currency.code}>{currency.code} - {currency.name}</option>)}</select> }
function Dashboard({ dashboard, from, to, setFrom, setTo, currencies, alert, setAlert, createAlert, remove, setPanel }) {
  const [section, setSection] = useState('overview')
  const activeAlerts = dashboard.alerts.filter((item) => item.status === 'active').length
  const show = (name) => { setSection(name); document.getElementById(`dash-${name}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }
  return <section className="dashboard-app">
    <aside className="dashboard-sidebar">
      <div className="sidebar-search">⌕ <span>Search workspace</span></div>
      <p className="nav-label">Workspace</p>
      <nav className="sidebar-nav">
        <button className={section === 'overview' ? 'active' : ''} onClick={() => show('overview')}><span>▦</span> Overview</button>
        <button className={section === 'alerts' ? 'active' : ''} onClick={() => show('alerts')}><span>◉</span> Rate alerts <b>{activeAlerts}</b></button>
        <button className={section === 'history' ? 'active' : ''} onClick={() => show('history')}><span>◷</span> History</button>
      </nav>
      <p className="nav-label">Quick access</p>
      <nav className="sidebar-nav muted-nav"><button onClick={() => setPanel('convert')}><span>⇄</span> Converter</button><button onClick={() => show('favorites')}><span>☆</span> Saved pairs</button></nav>
      <div className="sidebar-footer"><span className="online-dot" />Rates refresh hourly</div>
    </aside>
    <main className="dashboard-workspace">
      <header className="workspace-topbar"><div><p>PERSONAL DASHBOARD</p><h1>Good to see you.</h1></div><div><span className="secure-chip">● Secure session</span><button className="outline-button" onClick={() => setPanel('convert')}>Open converter ↗</button></div></header>
      <section className="overview-stats" id="dash-overview"><article><span>ACTIVE ALERTS</span><strong>{activeAlerts}</strong><small>tracking live rates</small></article><article><span>SAVED PAIRS</span><strong>{dashboard.favorites.length}</strong><small>ready to convert</small></article><article><span>CONVERSIONS</span><strong>{dashboard.conversions.length}</strong><small>in your history</small></article></section>
      <section className="content-panel alerts-panel" id="dash-alerts"><div className="panel-heading"><div><p>RATE MONITOR</p><h2>Rate alerts</h2><span>We’ll notify you when your target is reached.</span></div><span className="count-badge">{dashboard.alerts.length}</span></div><form className="alert-form" onSubmit={createAlert}><div className="alert-pair"><Currency value={from} setValue={setFrom} currencies={currencies} /><span>→</span><Currency value={to} setValue={setTo} currencies={currencies} /></div><div className="alert-rule"><select value={alert.condition} onChange={(e) => setAlert({ ...alert, condition: e.target.value })}><option value="above">Rises above</option><option value="below">Falls below</option></select><input required type="number" min="0.0001" step="0.0001" placeholder="Target rate" value={alert.target_rate} onChange={(e) => setAlert({ ...alert, target_rate: e.target.value })} /></div><button className="convert-button">Create alert</button></form><div className="alert-list">{dashboard.alerts.length ? dashboard.alerts.map((item) => <div className={`alert-item ${item.status}`} key={item.id}><div className="alert-icon">{item.status === 'triggered' ? '✓' : '↗'}</div><div className="alert-details"><strong>{item.from_currency} <span>→</span> {item.to_currency}</strong><p>{item.condition === 'above' ? 'Above' : 'Below'} <b>{Number(item.target_rate).toFixed(4)}</b></p></div><span className={`status-pill ${item.status}`}>{item.status}</span><button className="delete-button" onClick={() => remove(`/alerts/${item.id}`)} aria-label="Delete alert">×</button></div>) : <div className="empty-alert"><span>⌁</span><p>No alerts yet.<br /><small>Create one above to start tracking a rate.</small></p></div>}</div></section>
      <section className="content-panel" id="dash-history"><div className="panel-heading"><div><p>ACTIVITY</p><h2>Conversion history</h2></div></div>{dashboard.conversions.length ? dashboard.conversions.map((item) => <p className="history-row" key={item.id}><span>{Number(item.amount).toLocaleString()} {item.from_currency} → <strong>{Number(item.converted_amount).toLocaleString()} {item.to_currency}</strong></span><small>{new Date(item.created_at).toLocaleString()}</small><button onClick={() => remove(`/conversions/${item.id}`)}>×</button></p>) : <p className="muted">Your signed-in conversions will appear here.</p>}</section>
      <section className="content-panel favorites-panel" id="dash-favorites"><div className="panel-heading"><div><p>QUICK ACCESS</p><h2>Saved pairs</h2></div></div>{dashboard.favorites.length ? <div className="favorite-grid">{dashboard.favorites.map((item) => <div key={item.id}><button onClick={() => { setFrom(item.from_currency); setTo(item.to_currency); setPanel('convert') }}>{item.from_currency} → {item.to_currency}</button><button onClick={() => remove(`/favorites/${item.id}`)}>×</button></div>)}</div> : <p className="muted">Save a pair from the converter to see it here.</p>}</section>
      <footer className="workspace-footer">FXFlow <span>•</span> Exchange rates refresh hourly <span>•</span> Your account is protected</footer>
    </main>
  </section>
}
export default App
